{
 let a = 10;
 var b = 1;
}
try{
 console.log(a)
 console.log(b)
}
catch(err){
 console.log( err )
}
console.log(b)
